// Auto-generated by notion-orm push
// Do not edit manually

export const databaseMapping = {
  "Education": "81ee98cf-ac2b-4752-aa0d-e7a3923c193c",
  "81ee98cf-ac2b-4752-aa0d-e7a3923c193c": "c18d1af3-698c-4e3c-a3d1-2c8ec6933a13",
  "Blogs": "f080c246-de4d-45d3-a37b-e41cdcd6cb1c",
  "f080c246-de4d-45d3-a37b-e41cdcd6cb1c": "4f423620-c1ab-47a3-a781-4f0b88f3bce8",
  "Tasks": "1f092cd8-9cd6-4a54-bacd-22ab1f6140c4",
  "1f092cd8-9cd6-4a54-bacd-22ab1f6140c4": "10b1e0f5-c8ac-43bb-ae73-708e66f8f596",
  "Projects": "9cc6aeb9-4c42-440f-b1cb-14727520a6d7",
  "9cc6aeb9-4c42-440f-b1cb-14727520a6d7": "d1c1c0ba-0a8c-4a75-a37a-d47fc41c702f",
  "Pages": "58496060-3e28-4dac-bb9a-7a7be819a1e5",
  "58496060-3e28-4dac-bb9a-7a7be819a1e5": "3223662c-3d06-4c5b-91ea-749893bf3bdf",
} as const;

export type DatabaseMapping = typeof databaseMapping;
